[project]
name = "pydll-toolkit"
version = "0.1.0"
description = "python dll injection toolkit"
readme = "README.md"
requires-python = ">=3.13"
dependencies = ["pywin32>=310", "setuptools>=80.9.0"]

[tool.setuptools.packages.find]
where = ["src"]
